grails-app/domain/ggscms/Course.groovy
package ggscms

class Course {
    String name
    String shortDescription
    String description

    String toString() {
        "$name"
    }

    static hasMany = [memberships: Membership, chapters: Chapter, tests: Test, tasks: Task]

    static constraints = {
        name(blank: false, unique: true, size: 3..100)
        shortDescription(maxSize: 400, blank: false)
        description(maxSize: 10000, blank: false)
    }
}

grails-app/controllers/ggscms/CourseController.groovy
package ggscms

import grails.transaction.Transactional
import org.apache.shiro.SecurityUtils

@Transactional(readOnly = true)
class CourseController {

    def courses(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Course.list(params), model: [courseInstanceCount: Course.count()]
    }

    def create() {
        respond new Course(params)
    }

    @Transactional
    def save(Course courseInstance) {
        if (courseInstance == null) {
            notFound()
            return
        }

        if (courseInstance.hasErrors()) {
            respond courseInstance.errors, view: 'create'
            return
        }

        courseInstance.save flush: true


        flash.message = message(code: 'default.created.message', args: [message(code: 'course.label', default: 'Course'), courseInstance.name])
        redirect action: "courses"
    }

    def edit(Course courseInstance) {
        respond courseInstance
    }

    @Transactional
    def update(Course courseInstance) {
        if (courseInstance == null) {
            notFound()
            return
        }

        if (courseInstance.hasErrors()) {
            respond courseInstance.errors, view: 'edit'
            return
        }

        courseInstance.save flush: true

        flash.message = message(code: 'default.updated.message', args: [message(code: 'Course.label', default: 'Course'), courseInstance.name])
        redirect action: "courses"
    }

    @Transactional
    def delete(Course courseInstance) {

        if (courseInstance == null) {
            notFound()
            return
        }

        Membership.findAllByCourse(courseInstance).each {
            it.delete flush: true
        }

        courseInstance.delete flush: true

        flash.message = message(code: 'default.deleted.message', args: [message(code: 'Course.label', default: 'Course'), courseInstance.name])
        redirect action: "courses"
    }

    protected void notFound() {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'course.label', default: 'Course'), params.id])
        redirect action: "courses"
    }

    def users(Course courseInstance) {
        def users = User.where {
            memberships.course == courseInstance
        }.list().each {
            it.membership = Membership.findByUserAndCourse(it, courseInstance).access
        }

        if (params.order == 'asc') {
            users.sort { it.getProperty(params.sort) }
        } else if (params.order == 'desc') {
            users.sort { a, b ->
                b.getProperty(params.sort) <=> a.getProperty(params.sort)
            }
        }

        respond courseInstance, model: [users: users, course: courseInstance]
    }

    @Transactional
    def userAccessChange(Long id) {
        String userName = SecurityUtils.subject?.principal
        Course courseInstance = Course.findById(id)
        User manager = User.findByUsername("$userName")
        Membership managerMembership = Membership.findByUserAndCourse(manager, courseInstance)

        User user = User.findById(params.userId)
        Membership membership = Membership.findByUserAndCourse(user, courseInstance)

        if (params.changeAccess == "up") {
            switch (membership.access) {
                case Access.SUBSCRIBED: membership.access = Access.LISTENER
                    break
                case Access.LISTENER: membership.access = Access.STUDENT
                    break
                case Access.STUDENT:
                    if (managerMembership?.access == Access.TEACHER) {
                        break
                    }
                    membership.access = Access.TEACHER
                    break
            }
            membership.save(flush: true)
            user.membership = membership.access
            render(template: "/course/userAccess", model: [course: courseInstance, user: user])
        } else if (params.changeAccess == "down") {
            switch (membership.access) {
                case Access.TEACHER:
                    if (managerMembership?.access == Access.TEACHER) {
                        break
                    }
                    membership.access = Access.STUDENT
                    break
                case Access.STUDENT: membership.access = Access.LISTENER
                    break
                case Access.LISTENER: membership.access = Access.SUBSCRIBED
                    break
            }
            membership.save(flush: true)
            user.membership = membership.access
            render(template: "/course/userAccess", model: [course: courseInstance, user: user])
        }
    }

    @Transactional
    def subscribe(Course courseInstance) {
        String userName = SecurityUtils.subject?.principal
        User user = User.findByUsername("$userName")
        Membership membership = Membership.findByUserAndCourse(user, courseInstance)
        if (!membership) {
            new Membership(user: user, course: courseInstance, access: Access.SUBSCRIBED).save(flush: true)
            render(template: "/course/access", model: [course: courseInstance])
        } else if (membership.access == Access.SUBSCRIBED) {
            membership.delete(flush: true)
            render(template: "/course/access", model: [course: courseInstance])
        }
    }

    def tests(Course courseInstance) {
        String userName = SecurityUtils.subject?.principal
        User user = User.findByUsername("$userName")
        Membership membership = Membership.findByUserAndCourse(user, courseInstance)
        Test newTest = new Test(params)
        def tests = []

        if (membership?.access == Access.TEACHER || Role.findByName('administrator') in user.roles) {
            tests = Test.where {
                course == courseInstance
            }.list(params)
        } else tests = Test.where {
            course == courseInstance
            (isVisible == true) || (visibleOnTime == true && date < new Date())
        }.list(sort: 'number', order: 'asc')

        respond courseInstance, model: [tests: tests, newTest: newTest]
    }

    @Transactional
    def saveTest(Long id) {
        Course courseInstance = Course.findById(id)
        Test testInstance = new Test(params)

        def tests = Test.where {
            course == courseInstance
        }.list(params)

        if (!testInstance.validate()) {
            render(view: 'tests', model: [courseInstance: courseInstance, newTest: testInstance, tests: tests])
            return
        }

        testInstance.save flush: true

        flash.message = message(code: 'default.created.message', args: [message(code: 'test.label', default: 'Test'), testInstance.name])
        redirect action: 'addQuestionsToTest', id: id, params: [testId: testInstance.id]
    }

    def editTest(Long id) {
        Course courseInstance = Course.findById(id)
        Test testInstance = Test.findById(params.testId)

        def tests = Test.where {
            course == courseInstance
        }.list(params)

        render(view: 'test/editTest', model: [tests: tests, testInstance: testInstance, courseInstance: courseInstance])
    }

    @Transactional
    def updateTest(Long id) {
        Course courseInstance = Course.findById(id)
        Test testInstance = Test.findById(params.testId)

        def tests = Test.where {
            course == courseInstance
        }.list(params)

        testInstance.properties = params

        if (!testInstance.validate()) {
            render(view: 'test/editTest', model: [tests: tests, courseInstance: courseInstance, testInstance: testInstance])
            return
        }

        testInstance.save flush: true

        flash.message = message(code: 'default.updated.message', args: [message(code: 'Test.label', default: 'Test'), testInstance.name])
        redirect action: 'tests', id: id
    }

    @Transactional
    def deleteTest(Long id) {
        Test testInstance = Test.findById(params.testId)

        testInstance.delete flush: true

        flash.message = message(code: 'default.deleted.message', args: [message(code: 'Test.label', default: 'Test'), testInstance.name])
        redirect action: 'tests', id: id
    }

	@Transactional
    def testing(Long id) {
        Course courseInstance = Course.findById(id)
        Test testInstance = Test.findById(params.testId)
        String userName = SecurityUtils.subject?.principal
        User user = User.findByUsername("$userName")
        TestResult testResult = TestResult.findByUserAndTest(user, testInstance)
        def timeLimit = testInstance.timeLimit * 60 * 1000
        def timeLeft = testInstance.timeLimit * 60
        def currentTime = new Date().time

        if (testInstance.questions.size() == 0) {
            flash.message = message(code: 'default.testCompleted.message', args: [testInstance.name], default: "Test has not any questions.")
            redirect action: 'tests', id: id
            return
        }

        if (!testResult) {
            testResult = new TestResult(user: user, test: testInstance)

            testResult.save(flush: true)

            render view: "test/testing", model: [courseInstance: courseInstance, testInstance: testInstance, timeLeft: timeLeft, user: user]
        } else {
            def startTime = testResult.dateCreated.time

            def offTime = startTime + timeLimit

            if (offTime > currentTime) {
                timeLeft = (timeLimit - (currentTime - startTime)) / 1000
                render view: "test/testing", model: [courseInstance: courseInstance, testInstance: testInstance, timeLeft: timeLeft, user: user]
            } else {
                flash.message = message(code: 'default.testCompleted.message', args: [testInstance.name], default: "You have already completed {0} test")
                redirect action: 'tests', id: id
            }
        }
    }

    @Transactional
    def submitTest(Long id) {

grails-app/views/course/_access.gsp
<membership:subscribed courseId="${course.id}">
    <p><g:remoteLink class="btn btn-info" action="subscribe" id="${course.id}"
                     update="${course.id}">Unsubscribe now!</g:remoteLink></p>
</membership:subscribed>
<membership:none courseId="${course.id}">
    <p><g:remoteLink class="btn btn-primary" action="subscribe" id="${course.id}"
                     update="${course.id}">Subscribe now!</g:remoteLink></p>
</membership:none>

grails-app/views/course/_form.gsp
<%@ page import="ggscms.Course" %>

<div class="form-group ${hasErrors(bean: courseInstance, field: 'name', 'error')}">
	<label class="control-label" for="name">
		<g:message code="course.name.label" default="Name" />
	</label>
	<g:textField class="form-control" name="name" maxlength="100" required="" value="${courseInstance?.name}"/>
</div>

<div class="form-group ${hasErrors(bean: courseInstance, field: 'shortDescription', 'error')}">
	<label class="control-label" for="shortDescription">
		<g:message code="course.description.label" default="Short Description" />
	</label>
	<g:textArea class="form-control" name="shortDescription" rows="3" required="" value="${courseInstance.shortDescription}"/>
</div>

<div class="form-group ${hasErrors(bean: courseInstance, field: 'description', 'error')}">
	<label class="control-label" for="description">
		<g:message code="course.description.label" default="Description" />
	</label>
	<ckeditor:editor name="description">${courseInstance.description}</ckeditor:editor>
</div>

grails-app/views/course/_userAccess.gsp
<%@ page import="ggscms.Access; ggscms.Membership" %>
${user.membership}
<g:if test="${Membership.findByUserAndCourse(user,course).access == Access.SUBSCRIBED}">
    <g:remoteLink class="btn btn-success" action="userAccessChange" id="${course.id}"
                  update="${user.id}" params="[userId: user.id, changeAccess: 'up']">Up</g:remoteLink>
</g:if>
<g:elseif test="${Membership.findByUserAndCourse(user,course).access == Access.TEACHER}">
    <shiro:hasAnyRole in="['administrator']">
    <g:remoteLink class="btn btn-danger" action="userAccessChange" id="${course.id}"
                  update="${user.id}" params="[userId: user.id, changeAccess: 'down']">Down</g:remoteLink>
    </shiro:hasAnyRole>
</g:elseif>
<g:elseif test="${Membership.findByUserAndCourse(user,course).access == Access.STUDENT}">
    <shiro:hasAnyRole in="['administrator']">
        <g:remoteLink class="btn btn-success" action="userAccessChange" id="${course.id}"
                      update="${user.id}" params="[userId: user.id, changeAccess: 'up']">Up</g:remoteLink>
    </shiro:hasAnyRole>
    <g:remoteLink class="btn btn-danger" action="userAccessChange" id="${course.id}"
                  update="${user.id}" params="[userId: user.id, changeAccess: 'down']">Down</g:remoteLink>
</g:elseif>
<g:else>
    <g:remoteLink class="btn btn-success" action="userAccessChange" id="${course.id}"
                  update="${user.id}" params="[userId: user.id, changeAccess: 'up']">Up</g:remoteLink>
    <g:remoteLink class="btn btn-danger" action="userAccessChange" id="${course.id}"
                  update="${user.id}" params="[userId: user.id, changeAccess: 'down']">Down</g:remoteLink>
</g:else>

grails-app/views/course/courses.gsp
<%@ page import="ggscms.Course" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}"/>
    <title>GGSCMS</title>
    <style type="text/css">
    .navbar-brand {
        padding: 5px 5px;
    }
    </style>
</head>

<body>
<content tag="navbar">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><asset:image src="grails_logo.png" alt="Grails"/></a>
            </div>

            <div id="navbar" class="navbar-collapse collapse navbar-right">
                <g:render template="/common/topbar"/>
            </div><!--/.navbar-collapse -->
        </div>
    </nav>
</content>

<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-12">
        <g:if test="${flash.message}">
            <div class="alert alert-info" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                ${flash.message}</div>
        </g:if>
        <!--<p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
    </p>-->

    <g:each in="${courseInstanceList}" status="i" var="courseInstance">
        <membership:teacher courseId="${courseInstance.id}">
            <div class="col-xs-6 col-lg-3">
            <h2><g:link action="chapters"
                        id="${courseInstance.id}">${fieldValue(bean: courseInstance, field: "name")}</g:link></h2>
        </membership:teacher>
        <membership:student courseId="${courseInstance.id}">
            <div class="col-xs-6 col-lg-3">
            <h2><g:link action="chapters"
                        id="${courseInstance.id}">${fieldValue(bean: courseInstance, field: "name")}</g:link></h2>
        </membership:student>
        <membership:listener courseId="${courseInstance.id}">
            <div class="col-xs-6 col-lg-3">
            <h2><g:link action="chapters"
                        id="${courseInstance.id}">${fieldValue(bean: courseInstance, field: "name")}</g:link></h2>
        </membership:listener>
        <membership:subscribed courseId="${courseInstance.id}">
            <div class="col-xs-6 col-lg-3">
            <h2>${fieldValue(bean: courseInstance, field: "name")}</h2>
        </membership:subscribed>
        <membership:none courseId="${courseInstance.id}">
            <shiro:hasRole name="administrator">
                <div class="col-xs-6 col-lg-3">
                    <h2><g:link action="chapters"
                        id="${courseInstance.id}">${fieldValue(bean: courseInstance, field: "name")}</g:link></h2>
            </shiro:hasRole>
            <shiro:lacksRole name="administrator">
                <div class="col-xs-6 col-lg-3">
                <h2>${fieldValue(bean: courseInstance, field: "name")}</h2>
            </shiro:lacksRole>
        </membership:none>
        <shiro:notUser>
            <div class="col-xs-6 col-lg-3">
            <h2>${fieldValue(bean: courseInstance, field: "name")}</h2>
        </shiro:notUser>

        <p>${fieldValue(bean: courseInstance, field: "shortDescription")}</p>

        <p><button type="button" class="btn btn-default" data-toggle="modal" data-target="#courseModal${courseInstance.id}">
            More info
        </button></p>

        <!-- Modal -->
        <div class="modal fade" id="courseModal${courseInstance.id}" tabindex="-1" role="dialog" aria-labelledby="courseModal${courseInstance.id}Label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="courseModal${courseInstance.id}Label">${fieldValue(bean: courseInstance, field: "name")}</h4>
                    </div>
                    <div class="modal-body">
                        ${raw(courseInstance.description)}
                    </div>
                    <div class="modal-footer">
        <shiro:hasAnyRole in="['administrator']">
                        <g:link class="btn btn-warning" action="edit" resource="${courseInstance}"><g:message
                                code="default.button.edit.label"
                                default="Edit"/></g:link>
                        <g:link class="btn btn-danger" action="delete" resource="${courseInstance}"
                                onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
                            ${message(code: 'default.button.delete.label', default: 'Delete')}
                        </g:link>
        </shiro:hasAnyRole>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="${courseInstance.id}">
            <membership:teacher courseId="${courseInstance.id}">
                <p><button type="button" class="btn btn-danger" disabled="disabled">You are a teacher!</button></p>
            </membership:teacher>
            <membership:student courseId="${courseInstance.id}">
                <p><button type="button" class="btn btn-warning" disabled="disabled">You are a student!</button></p>
            </membership:student>
            <membership:listener courseId="${courseInstance.id}">
                <p><button type="button" class="btn btn-success" disabled="disabled">You are a listener!</button></p>
            </membership:listener>
            <membership:subscribed courseId="${courseInstance.id}">

                <p><g:remoteLink class="btn btn-info" action="subscribe" id="${courseInstance.id}"
                                 update="${courseInstance.id}">Unsubscribe now!</g:remoteLink></p>

            </membership:subscribed>
            <membership:none courseId="${courseInstance.id}">

                <p><g:remoteLink class="btn btn-primary" action="subscribe" id="${courseInstance.id}"
                                 update="${courseInstance.id}">Subscribe now!</g:remoteLink></p>

            </membership:none>
        <!-- Button trigger modal -->
        </div>
        </div><!--/.col-xs-6.col-lg-4-->

    </g:each>

</div><!--/.col-xs-12.col-sm-9-->
</div><!--/row-->
    <shiro:hasRole name="administrator">
        <nav class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#courses-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="courses-collapse">
                <ul class="nav navbar-nav">
                    <g:link class="btn btn-success navbar-btn" action="create"><g:message code="default.new.label"
                                                                                              args="[entityName]"/></g:link>
                </ul>


                <ul class="nav navbar-nav navbar-right">
                    <g:link class="btn btn-primary navbar-btn" controller="user" action="index">All Users</g:link>
                </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
    </shiro:hasRole>
</body>
</html>

grails-app/views/course/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
		<style type="text/css">
		.navbar-brand {
			padding: 5px 5px;
		}
		</style>
	</head>
	<body>
	<g:if test="${flash.message}">
		<div class="alert alert-info" role="alert">${flash.message}</div>
	</g:if>
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title"><g:message code="default.create.label" args="[entityName]" /></h3>
		</div>
		<g:form url="[resource:courseInstance, action:'save']" >
			<div class="panel-body">
				<g:hasErrors bean="${courseInstance}">
					<ul class="list-group">
						<g:eachError bean="${courseInstance}" var="error">
							<li <g:if test="${error in org.springframework.validation.FieldError}">class="list-group-item list-group-item-danger"</g:if>><g:message
									error="${error}"/></li>
						</g:eachError>
					</ul>
				</g:hasErrors>

				<g:hiddenField name="version" value="${courseInstance?.version}"/>

				<g:render template="form"/>

			</div>
			<div class="panel-footer">
				<g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.create.label', default: 'Create')}" />
			</div>
		</g:form>
	</div>
	</body>
</html>

grails-app/views/course/edit.gsp
<%@ page import="ggscms.Course" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <style type="text/css">
    .navbar-brand {
        padding: 5px 5px;
    }
    </style>
</head>

<body>
<g:if test="${flash.message}">
    <div class="alert alert-info" role="alert">${flash.message}</div>
</g:if>
<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title"><g:message code="default.edit.label" args="[courseInstance.name]"/></h3>
    </div>
    <g:form url="[resource: courseInstance, action: 'update']">
        <div class="panel-body">
            <g:hasErrors bean="${courseInstance}">
                <ul class="list-group">
                    <g:eachError bean="${courseInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">class="list-group-item list-group-item-danger"</g:if>><g:message
                                error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>

            <g:hiddenField name="version" value="${courseInstance?.version}"/>

            <g:render template="form"/>

        </div>
        <div class="panel-footer">
            <g:actionSubmit class="btn btn-warning" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/course/rating.gsp
<%@ page import="ggscms.Rating; ggscms.TestResult; org.springframework.validation.FieldError; ggscms.Color; ggscms.Chapter; ggscms.Course" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'course.label', default: 'Course')}"/>
    <title>Rating</title>
</head>

<body>
<content tag="navbar">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><g:fieldValue bean="${courseInstance}" field="name"/></a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><g:link action="chapters" id="${courseInstance.id}">Course program</g:link></li>
                    <li><g:link action="lessons" id="${courseInstance.id}">Lessons</g:link></li>
                    <li><g:link action="homeworks" id="${courseInstance.id}">Homeworks</g:link></li>
                    <li><g:link action="tests" id="${courseInstance.id}">Tests <span class="badge"><tests:count/></span></g:link></li>
                    <li class="active"><g:link action="rating" id="${courseInstance.id}">Rating</g:link></li>
                    <membership:teacherOrAdmin>
                        <li><g:link action="users" id="${courseInstance.id}">Users</g:link></li>
                    </membership:teacherOrAdmin>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <g:render template="/common/topbar"/>
                </ul>
            </div><!--/.navbar-collapse -->
        </div>
    </nav>
</content>

<g:if test="${flash.message}">
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        ${flash.message}</div>
</g:if>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

        <g:each in="${courseInstance?.tests}" status="i" var="testInstance">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="collapseListGroupHeading${i}">
                    <h4 id="-collapsible-list-group-" class="panel-title">
                        <a class="" data-toggle="collapse" href="#collapseListGroup${i}" aria-expanded="true"
                           aria-controls="collapseListGroup${i}">
                            <strong>${fieldValue(bean: testInstance, field: "number")}</strong>
                            ${fieldValue(bean: testInstance, field: "name")}
                        </a>
                        <a class="anchorjs-link" href="#-collapsible-list-group-"><span class="anchorjs-icon"></span>
                        </a></h4>
                </div>

                <div style="" aria-expanded="true" id="collapseListGroup${i}" class="panel-collapse collapse"
                     role="tabpanel" aria-labelledby="collapseListGroupHeading${i}">

                    <table class="table table-striped table-condensed">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Full Name</th>
                            <th>Rating %</th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each in="${TestResult.findByTest(testInstance)?.list(sort: 'result', order: 'desc')}"
                                status="y" var="testResultInstance">
                            <tr>
                                <th scope="row">${y + 1}</th>
                                <td>${testResultInstance.user.fullName}</td>
                                <td>${testResultInstance.result}</td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>
        </g:each>
        <div class="panel panel-danger">
            <div class="panel-heading" role="tab" id="collapseListGroupHeading${i}">
                <h4 id="-collapsible-list-group-" class="panel-title">
                    <a class="" data-toggle="collapse" href="#collapseListGroup${i}" aria-expanded="true"
                       aria-controls="collapseListGroup${i}">
                        <strong>Full Rating</strong>
                    </a>
                    <a class="anchorjs-link" href="#-collapsible-list-group-"><span class="anchorjs-icon"></span></a>
                </h4>
            </div>

            <div style="" aria-expanded="true" id="collapseListGroup${i}" class="panel-collapse collapse in"
                 role="tabpanel" aria-labelledby="collapseListGroupHeading${i}">

                <table class="table table-striped table-condensed">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Full Name</th>
                        <th>Completed Tests</th>
                        <th>Rating %</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${Rating.findByCourse(courseInstance)?.list(sort: 'result', order: 'desc')}"
                            status="y" var="ratingInstance">
                        <tr>
                            <th scope="row">${y + 1}</th>
                            <td>${ratingInstance.user.fullName}</td>
                            <td>${ratingInstance.completedTests}</td>
                            <td>${ratingInstance.result}</td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>
</html>