grails-app/domain/ggscms/User.groovy
package ggscms

class User {
    Date dateCreated
    String username
    String passwordHash
    String fullName
    String email
    String phone
    String membership

    static transients = ['membership']

    String toString() {
        "$username"
    }

	static mapping = { 
		table 'users'
	 }

    static hasMany = [memberships: Membership, roles: Role, permissions: String]

    static constraints = {
        username(nullable: false, blank: false, unique: true)
        fullName blank: false
        email email: true, blank: false
        phone blank: false
    }
}

grails-app/controllers/ggscms/UserController.groovy
package ggscms

import grails.transaction.Transactional
import org.apache.shiro.crypto.hash.Sha256Hash

@Transactional(readOnly = true)
class UserController {

    def simpleCaptchaService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model: [userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    @Transactional
    def userAccessChange(User userInstance) {
        Course courseInstance = Course.findById(params.courseId)
        Membership membership = Membership.findByUserAndCourse(userInstance, courseInstance)

        if (!membership && params.changeAccess == "up") {
            membership = new Membership(course: courseInstance, user: userInstance, access: Access.SUBSCRIBED)
            membership.save(flush: true)
            render(template: "/user/userAccess", model: [course: courseInstance, user: userInstance])
            return
        }

        if (params.changeAccess == "up") {
            switch (membership.access) {
                case Access.SUBSCRIBED: membership.access = Access.LISTENER
                    break
                case Access.LISTENER: membership.access = Access.STUDENT
                    break
                case Access.STUDENT: membership.access = Access.TEACHER
                    break
            }
            membership.save(flush: true)
            render(template: "/user/userAccess", model: [course: courseInstance, user: userInstance])
        } else if (params.changeAccess == "down") {
            switch (membership.access) {
                case Access.TEACHER: membership.access = Access.STUDENT
                    membership.save(flush: true)
                    break
                case Access.STUDENT: membership.access = Access.LISTENER
                    membership.save(flush: true)
                    break
                case Access.LISTENER: membership.access = Access.SUBSCRIBED
                    membership.save(flush: true)
                    break
                case Access.SUBSCRIBED: membership.delete(flush: true)
                    break
            }
            render(template: "/user/userAccess", model: [course: courseInstance, user: userInstance])
        }
    }

    def register() {}

    @Transactional
    def registration() {
        def user = new User(username: params.username,
                passwordHash: new Sha256Hash(params.password).toHex(),
                fullName: params.fullName,
                email: params.email,
                phone: params.phone)
        def userRole = Role.findByName("user")
        user.addToRoles(userRole)

        boolean captchaValid = simpleCaptchaService.validateCaptcha(params.captcha)

        def errors = [:]

        if (captchaValid) {
            if (params.password != params.confirm) {
                flash.message = "The two passwords you entered dont match!"
                errors = [password: "error"]
                render(view: 'register', model: [user: user, errors: errors])
            } else if (!(params.password.size() in 8..16)) {
                flash.message = "Password must contain 8..16 characters!"
                errors = [password: "error"]
                render(view: 'register', model: [user: user, errors: errors])
            } else {
                if (user.save()) {
                    redirect(controller: "auth", action: "signIn", params: [username: params.username, password: params.password])
                } else {
                    flash.user = user
                    render(view: 'register', model: [user: user, errors: errors])
                }
            }
        } else {
            flash.message = "Access code did not match."
            errors = [captcha: "error"]
            render(view: 'register', model: [user: user, errors: errors])
        }
    }
}

grails-app/views/user/_userAccess.gsp
<%@ page import="ggscms.Access; ggscms.Membership" %>
<div class="row">
    <div class="col-xs-2 col-sm-2">
        ${Membership.findByUserAndCourse(user,course) ? Membership.findByUserAndCourse(user,course).access.value : 'none'}
    </div>

    <div class="col-xs-3 col-sm-3 text-right">
        <g:if test="${!Membership.findByUserAndCourse(user,course)}">
            <g:remoteLink class="btn btn-success" action="userAccessChange" resource="${user}"
                          update="${course.id}" params="[courseId: course.id, changeAccess: 'up']">Up</g:remoteLink>
        </g:if>
        <g:elseif test="${Membership.findByUserAndCourse(user,course).access == Access.TEACHER}">
                <g:remoteLink class="btn btn-danger" action="userAccessChange" resource="${user}"
                              update="${course.id}" params="[courseId: course.id, changeAccess: 'down']">Down</g:remoteLink>
        </g:elseif>
        <g:else>
            <g:remoteLink class="btn btn-success" action="userAccessChange" resource="${user}"
                          update="${course.id}" params="[courseId: course.id, changeAccess: 'up']">Up</g:remoteLink>
            <g:remoteLink class="btn btn-danger" action="userAccessChange" resource="${user}"
                          update="${course.id}" params="[courseId: course.id, changeAccess: 'down']">Down</g:remoteLink>
        </g:else>
    </div>
</div>

grails-app/views/user/index.gsp
<%@ page import="ggscms.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <style type="text/css">
    .navbar-brand {
        padding: 5px 5px;
    }
    </style>
</head>

<body>

<g:if test="${flash.message}">
    <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        ${flash.message}</div>
</g:if>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>

            <g:sortableColumn property="username" title="${message(code: 'user.username.label', default: 'Username')}"/>

            <g:sortableColumn property="fullName"
                              title="${message(code: 'user.fullName.label', default: 'Full Name')}"/>

            <g:sortableColumn property="email" title="${message(code: 'user.email.label', default: 'Email')}"/>

            <g:sortableColumn property="phone" title="${message(code: 'user.phone.label', default: 'Phone')}"/>

            <g:sortableColumn property="dateCreated"
                              title="${message(code: 'user.dateCreated.label', default: 'Date Created')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${userInstanceList}" status="i" var="userInstance">
            <tr>

                <td><g:link action="show"
                            id="${userInstance.id}">${fieldValue(bean: userInstance, field: "username")}</g:link></td>

                <td>${fieldValue(bean: userInstance, field: "fullName")}</td>

                <td>${fieldValue(bean: userInstance, field: "email")}</td>

                <td>${fieldValue(bean: userInstance, field: "phone")}</td>

                <td><g:formatDate date="${userInstance.dateCreated}"/></td>

            </tr>
        </g:each>
        </tbody>
    </table>
</div>

<div class="pagination">
    <g:paginate total="${userInstanceCount ?: 0}"/>
</div>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#courses-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="courses-collapse">
            <ul class="nav navbar-nav">
                <g:link class="btn btn-success navbar-btn" controller="course" action="create">New Course</g:link>
            </ul>


            <ul class="nav navbar-nav navbar-right">
                <g:link class="btn btn-primary navbar-btn" controller="user" action="index">All Users</g:link>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

</body>
</html>

grails-app/views/user/register.gsp
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="layout" content="main"/>
    <title>Registration</title>
    <style type="text/css">
    .navbar-brand {
        padding: 5px 5px;
    }
    </style>
</head>

<body>
<g:if test="${flash.message}">
    <div class="alert alert-danger" role="alert">${flash.message}</div>
</g:if>
<g:hasErrors bean="${user}">
    <ul class="list-group">
        <g:eachError bean="${user}" var="error">
            <li <g:if test="${error in org.springframework.validation.FieldError}">class="list-group-item list-group-item-danger"</g:if>><g:message error="${error}"/></li>
        </g:eachError>
    </ul>
</g:hasErrors>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1 class="text-center">Register</h1>
        <g:form action="registration" method="post">
            <div class="form-group ${hasErrors(bean: user, field: 'username', 'errors')}">
                <label class="control-label" for="username">Username:</label>
                <input class="form-control" type="text" name="username" value="${user?.username}"/>
            </div>

            <div class="form-group ${errors?.password}">
            <label for="password">Password:</label>
            <input class="form-control" type="password" name="password" value=""/>
            </div>

            <div class="form-group ${errors?.password}">
                <label for="confirm">Confirm Password:</label>
                <input class="form-control" type="password" name="confirm" value=""/>
            </div>

            <div class="form-group ${hasErrors(bean: user, field: 'fullName', 'errors')}">
            <label for="fullName">Full Name:</label>
            <input class="form-control" type="text" name="fullName" value="${user?.fullName}"/>
            </div>

            <div class="form-group ${hasErrors(bean: user, field: 'email', 'errors')}">
                <label for="email">Email:</label>
                <input class="form-control" type="text" name="email" value="${user?.email}"/>
            </div>

            <div class="form-group ${hasErrors(bean: user, field: 'phone', 'errors')}">
                <label for="phone">Phone:</label>
                <input class="form-control" type="text" name="phone" value="${user?.phone}"/>
            </div>

            <div class="form-group ${errors?.captcha}">
                <label for="code">Enter Code:</label>
                <img src="${createLink(controller: 'simpleCaptcha', action: 'captcha')}"/>
                <g:textField class="form-control" name="captcha"/><br/>
            </div>

            <g:actionSubmit class="btn btn-default" value="Register" action="registration"/>
        </g:form>
    </div>
</div>

</body>
</html>

grails-app/views/user/show.gsp
<%@ page import="ggscms.Membership; ggscms.Course; ggscms.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <style type="text/css">
    .navbar-brand {
        padding: 5px 5px;
    }
    </style>
</head>

<body>

<div class="table-responsive">
    <table class="table table-striped">
        <caption>${userInstance.username} Memberships</caption>
        <thead>
        <tr>

            <th>#</th>
            <th>Course</th>
            <th>Membership</th>

        </tr>
        </thead>
        <tbody>
        <g:each in="${Course.findAll()?.sort() { it.id }}" status="i" var="courseInstance">
            <tr>

                <th scope="row">${i + 1}</th>

                <td>${fieldValue(bean: courseInstance, field: "name")}</td>

                <td>

                    <div class="container-fluid" id="${courseInstance.id}">
                        <g:render template="userAccess" model="[user: userInstance, course: courseInstance]"/>
                    </div>

                </td>

            </tr>
        </g:each>
        </tbody>
    </table>
</div>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#courses-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="courses-collapse">
            <ul class="nav navbar-nav">
                <g:link class="btn btn-success navbar-btn" controller="course" action="create">New Course</g:link>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <g:link class="btn btn-primary navbar-btn" controller="user" action="index">All Users</g:link>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

</body>
</html>