grails-app/controllers/ggscms/AuthController.groovy
package ggscms

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken

class AuthController {
    def shiroSecurityManager

    def index() { redirect(action: "login", params: params) }

    def login() {
        return [username: params.username, rememberMe: (params.rememberMe != null)]
    }

    def signIn() {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }

        try {
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            redirect(controller: "course", action: "courses")
        }
        catch (AuthenticationException ex) {
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut() {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
    }
}

grails-app/views/common/_footer.gsp
<footer>
    <p>Groovy and Grails Student CMS for GEEKHUB.CK.UA<br/>
    &copy; 2015 Pavel Bezpalov
    </p>
</footer>

grails-app/views/common/_navbar.gsp
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><asset:image src="grails_logo.png" alt="Grails"/></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse navbar-right">
            <g:render template="/common/topbar"/>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

grails-app/views/common/_topbar.gsp
<shiro:user>
    <g:link class="btn btn-warning navbar-btn navbar-right" controller="auth" action="signOut"><g:message code="topbar.logout"/></g:link>
    <p class="navbar-text navbar-right"><shiro:principal/>&nbsp;&nbsp;&nbsp;</p>
</shiro:user>
<shiro:notUser>
        <g:link class="btn btn-success navbar-btn" controller="auth" action="login">Login</g:link>
        <g:link class="btn btn-info navbar-btn" controller="user" action="register">Register</g:link>
</shiro:notUser>